/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	RCC_AHB1ENR_t volatile *const pClkCntlReg = (RCC_AHB1ENR_t *) 0x40023830;
	GPIOx_MODE_t volatile *const pGpioDMode = (GPIOx_MODE_t *) 0x40020C00;
	GPIOx_PUPDR_t volatile *const pGpioDPupdMode = (GPIOx_PUPDR_t*) 0x40020C0C;
	GPIOx_ODR_t volatile *const pGpioDOut = (GPIOx_ODR_t *) 0x40020C14;
	GPIOx_IDR_t const volatile *const pGpioDIn = (GPIOx_IDR_t *) 0x40020C10;

	init(pClkCntlReg,pGpioDPupdMode, pGpioDMode);

    /* Loop forever */
	while(1) {
		//read col1
		readKeypadRow(pGpioDIn, pGpioDOut, row1);
		readKeypadRow(pGpioDIn, pGpioDOut, row2);
		readKeypadRow(pGpioDIn, pGpioDOut, row3);
		readKeypadRow(pGpioDIn, pGpioDOut, row4);
	}
}

void init(RCC_AHB1ENR_t volatile *const pClkCtrlReg,GPIOx_PUPDR_t volatile *const pGpioxPUPDR,
		GPIOx_MODE_t volatile *const pGpioxMode) {
	//enable GPIOD clock
	pClkCtrlReg->gpio_d_en=1;
	//enable pin0..pin3 to have pull up resistor
	pGpioxPUPDR->pin_0 = 0b01;
	pGpioxPUPDR->pin_1 = 0b01;
	pGpioxPUPDR->pin_2 = 0b01;
	pGpioxPUPDR->pin_3 = 0b01;
	//enable pin0..pin3 to be input mode
	pGpioxMode->pin_0=0b00;
	pGpioxMode->pin_1=0b00;
	pGpioxMode->pin_2=0b00;
	pGpioxMode->pin_3=0b00;
	//enable pin3..pin5 to be output mode
	pGpioxMode->pin_4=0b01;
	pGpioxMode->pin_5=0b01;
	pGpioxMode->pin_6=0b01;
	pGpioxMode->pin_7=0b01;
}

void readKeypadRow(const volatile GPIOx_IDR_t *const pGpioDIn,
		volatile GPIOx_ODR_t *const pGpioDOut, rows_t checkCol) {
	//read col1
	switch (checkCol) {
	case row1:
		pGpioDOut->pin_4 = 0;
		pGpioDOut->pin_5 = 1;
		pGpioDOut->pin_6 = 1;
		pGpioDOut->pin_7 = 1;
		break;
	case row2:
		pGpioDOut->pin_4 = 1;
		pGpioDOut->pin_5 = 0;
		pGpioDOut->pin_6 = 1;
		pGpioDOut->pin_7 = 1;
		break;
	case row3:
		pGpioDOut->pin_4 = 1;
		pGpioDOut->pin_5 = 1;
		pGpioDOut->pin_6 = 0;
		pGpioDOut->pin_7 = 1;
		break;
	case row4:
		pGpioDOut->pin_4 = 1;
		pGpioDOut->pin_5 = 1;
		pGpioDOut->pin_6 = 1;
		pGpioDOut->pin_7 = 0;
		break;
	default:
		break;
	};
	if (pGpioDIn->pin_0 == 0) {
		delay();
		printf("%i1 was pressed\n", checkCol);
	}
	if (pGpioDIn->pin_1 == 0) {
		delay();
		printf("%i1 was pressed\n", checkCol);
	}
	if (pGpioDIn->pin_2 == 0) {
		delay();
		printf("%i1 was pressed\n", checkCol);
	}
	if (pGpioDIn->pin_3 == 0) {
		delay();
		printf("%i1 was pressed\n", checkCol);
	}

}
void delay() {
	for(uint32_t volatile i =0 ; i < 300000 ; i++);
}
