/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t volatile *const pClkCtrlReg = (uint32_t*) 0x40023830;

	uint32_t volatile *const pPortAModeReg = (uint32_t*) 0x40020000;
	uint32_t volatile *const pPortAOutReg = (uint32_t*) 0x40020014;

	uint32_t volatile *const pPortDModeReg = (uint32_t*) 0x40020C00;
	uint32_t const volatile *const pPortDInReg = (uint32_t*) 0x40020C10;

	//enable the clock on AHB1 GPIOA
	*pClkCtrlReg |= 0b1;
	//and GPIOD
	*pClkCtrlReg |= (0b1 << 3);

	//making PD0 is on input mode =00
	*pPortDModeReg &= ~(0b11 << 0);

	//making PA1 is on output mode =01
	*pPortAModeReg &= ~(0b11 << 2);
	*pPortAModeReg |= (0b1 << 2);


	while(1) {
		if ((*pPortDInReg & 0b1) == 1) {
			*pPortAOutReg  &= ~(0b1 << 1);
		} else {
			*pPortAOutReg  |= (0b1 << 1);
		}

	}


}
