/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *pClkCtrlReg = (uint32_t*) 0x40023830;
	uint32_t *pPortAModeReg = (uint32_t*) 0x40020000;
	uint32_t *pPortAOutReg = (uint32_t*) 0x40020014;

	//enable the clock on AHB1 GPIOA
	*pClkCtrlReg |= 0b1;
	//making PA1 is on output mode
	*pPortAModeReg &= ~(0b11 << 2);
	*pPortAModeReg |= (0b1 << 2);

	//toggle the LED of PA1
	 while(1) {
		 *pPortAOutReg  |= (0b1 << 1);
		 for (int i=0; i<1000; i++);
		 *pPortAOutReg  &= ~(0b1 << 1);
		 for (int i=0; i<1000; i++);
	 }
}
